### ISSUE TITLE
netstandard1.3 support

### ISSUE THREAD

**Issue by riley-van-hengstum** [tsolarin/readline#36]
Is there a reason the latest version (v2.0.0) dropped netstandard1.3 support? The github page still mentions netstandard1.3 support.

**Comment by tonerdo** [comment]
@Jaap-van-Hengstum I intended to have it support as many platforms as possible. Is there a particular use case where netstandard2.0 support isn't working for you?

**Comment by Latency** [comment]
Fixed!!!
----------
@Jaap-van-Hengstum:
I had dropped Standard v1.3, since it has been replaced by v2.0.

Framework v4.7.x requires Windows 10 (creators or fall season) build v1703 and newer.

For backwards compatibility, Framework v4.5 / v4.6.2 & Standard v1.3 added into this build.

Requests to sustain anything older than that will be rejected!!!

References:
------------
Issue [#34](https://github.com/tonerdo/readline/pull/34)

**Comment by Latency** [comment]
@tonerdo:  Request to change authors/owners metadata attributes  -  (community vs personalized)???

**Comment by riley-van-hengstum** [comment]
@tonerdo 

The reason for netstandard1.3 is that I'm still using .NET Framework 4.6.2 with VS2015.

I'm not sure if you can use netstandard2 packages with that configuration, but it doesn't work out-of-the-box. I get the following message trying to install from NuGet:

> Could not install package 'ReadLine 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

### Update
I got the NuGet import to work by first installing the latest NuGet (from [here](https://www.nuget.org/downloads)) and then installing netstandard2 support for VS2015 (from [here](https://aka.ms/netstandard-build-support-netfx)).

### Update 2
Importing the 'ReadLine 2.0.0' package using NuGet worked, but now I get build errors like:

> Error CS1703: Multiple assemblies with equivalent identity have been imported: 'C:\Program Files (x86)\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\net461\ref\System.Xml.XmlSerializer.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.2\Facades\System.Xml.XmlSerializer.dll'. Remove one of the duplicate references.

I have yet to look into that. 
So netstandard1.3 support would still be appreciated.

**Comment by Latency** [comment]
@Jaap-van-Hengstum: 

You are getting binding redirect version conflicts between your packages.   If your dependency assemblies are not targeted to support the newer framework or have mismatched /older versions...  it will break.

Read this page [here](https://msdn.microsoft.com/en-us/magazine/mt842506.aspx),

If you are not planning on x-targeting your project, I recommend using the v4.5-4.7.1 framework in leu of the Standard BCL 1.3/2.0 or Core 2.0.

The Standard 1.3 has been replaced with 2.0.  Therefore, you should migrate any projects to adhere to v2.0 conventions.

**Can you use the package I built tonight found [here](https://github.com/Latency/ReadLine/tree/master/artifacts) and retry it?**

You will need to add a local path reference in the NuGet package manager settings pointing to where the .nupkg file location is on your machine.

Visual Studio |   Tools -> Options -> NuGet Package Manager -> Package Sources
Add a new item in the list (which can also be added in your solution's 'NuGet.config' file).

A: Give it any name you wish
P: \<Folder Location\>

Next, open your NuGet Package Manager in your projects dependencies and select the new entry from the combo-box located top-right.

Manually update the version of the package this way, until @tonerdo publishes the new release on 'nuget.org'.

**Comment by Whivel** [comment]
> ## Fixed!!!
> @Jaap-van-Hengstum:
> I had dropped Standard v1.3, since it has been replaced by v2.0.
> 
> Framework v4.7.x requires Windows 10 (creators or fall season) build v1703 and newer.
> 
> For backwards compatibility, Framework v4.5 / v4.6.2 & Standard v1.3 added into this build.
> 
> Requests to sustain anything older than that will be rejected!!!
> 
> ## References:
> Issue [#34](https://github.com/tonerdo/readline/pull/34)

Net Standard does not work in that way. 
Net Standard is like an interface and a newer standard includes older ones. So you should use the lower Net standard which fits with your requirements: older standards are not really "older", but they only have fewer classes.
That is also the best practice recommendation from Microsoft.

**Comment by riley-van-hengstum** [comment]
Closing this for it's a stale issue.
